name: house_discover

channels:
  - conda-forge
  - rexchange

dependencies:
  - flake8 >= 3.8.4
  - isort >= 5.6.4
  - jupyter >= 1.0.0
  - matplotlib >= 3.3.3
  - pandas >= 0.24.2
  - pillow >= 8.0.1
  - pip >= 20.3.3
  - python >= 3.7.9
  - rexsettings >= 1.34.0
  - ruamel.yaml >= 0.16.12
  - scipy >= 1.5.3
  - seaborn >= 0.11.1
  - shap >= 0.37.0
  - sqlalchemy >= 1.3.22
  - tensorflow >= 1.14.0
  - textblob >= 0.15.3
  - torch >= 1.7.1
  - tqdm >= 4.54.1
  - pip:
      - google-colab >= 1.0.0
      - psycopg2-binary >= 2.8.6
      - surprise >= 0.1
