name: house_discover

channels:
  - conda-forge
  - rexchange

dependencies:
  - flake8 >= 3.8.4
  - isort >= 5.6.4
  - jupyter >= 1.0.0
  - matplotlib >= 3.3.3
  - pandas >= 1.1.5
  - pip >= 20.3.1
  - python >= 3.7.9
  - rexsettings >= 1.34.0
  - ruamel.yaml >= 0.16.12
  - scipy >= 1.5.3
  - seaborn >= 0.11.1
  - shap >= 0.37.0
  - sqlalchemy >= 1.3.20
  - tensorflow >= 1.14.0
  - tqdm >= 4.54.1
  - pip:
      - psycopg2-binary >= 2.8.6
